### PR TITLE
Find best move

### PR DESCRIPTION
**Pull request by binarybrain11**
This branch is really stable and performs better than main. Next improvement should probably be a position table with zobrist hashing which should go in another branch.

### CODE REVIEW

**Comment by binarybrain11** [comment]
This might be a good point to start giving lefoux a version number, like this merge seems like a good candidate for version 0.

**Review by Chewt — CHANGES_REQUESTED** [review]
I believe these will need to be changed to write() for the io redirection to work.

**Comment by Chewt** [comment]
> This might be a good point to start giving lefoux a version number, like this merge seems like a good candidate for version 0.

Good idea. I think we should follow this guide for versioning https://semver.org/ and either start with v1.0.0 or v0.0.1

**Comment by binarybrain11** [comment]
I can't see what you're referring to when you say "these", can you make a comment on the lines or submit a commit with the changes?

**Comment by Chewt** [comment]
oh weird, it should have included the lines I selected but its lines 
42 and 43 of uci.h 

the printdebug() function

**Review by Chewt — COMMENTED** [review]
Testing selecting the lines

**Comment by binarybrain11** [comment]
Incorporated suggestions from code review and initialized version number.

**Comment by binarybrain11** [comment]
Hmm Github actions are weird lmao. I think once this gets merged with main it'll pass the checks.

**Pull request merged**
